Nkorchi
yrahul3910/mk8d pull request #10
Opened 2023-03-21 16:14 UTC by korchiev

2023-03-21 17:24 UTC, yrahul3910 requested changes
Please also fix `ruff` errors.

2023-03-21 17:24 UTC, yrahul3910 commented on main.py
> +from src.recommenders.bo import Myrecommender
Rename to `BORecommender`.

2023-03-21 17:24 UTC, yrahul3910 commented on main.py
> +#TODO
Prefer double quotes on the outside for this case. If `ruff` complains, you can disable it for this line. PEP20: Readability counts.

2023-03-21 17:24 UTC, yrahul3910 commented on main.py
> +#TODO
Also: Remove TODO--it's unclear what the todo is.

2023-03-21 17:24 UTC, yrahul3910 commented on main.py
> +print('Final recommendation:', final)
Should we refactor this to one line?

2023-03-21 17:24 UTC, yrahul3910 commented on output.json
This file should not be committed. Add it to `.gitignore` and remove this file.

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/base.py
> +    def __init__(self, stats_df: pd.DataFrame, player_name):
Add a type hint for `player_name`.

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/base.py
> +    def __recommend(self, player_name):
To avoid [name mangling](https://docs.python.org/3/tutorial/classes.html#private-variables), this name should idiomatically be named `_recommend`. This will also fix the issue you're having in the derived class.

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/base.py
> +    def __recommend(self, player_name):
`player_name` needs a type hint.

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/base.py
> +    def dump_to(self, filename, var_names):
Follow [PEP8](http://www.python.org/dev/peps/pep-0008/): This should be named `_dump_to`.

> `_single_leading_underscore`: weak "internal use" indicator. E.g. `from M import *` does not import objects whose name starts with an underscore.

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/bi.py
> +    __name__ = 'bayesian inference'
Newline after this

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/bi.py
> +    def __recommend(self):
`_recommend`

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/bo.py
> +    def _BaseRecommender__recommend(self):
Refactor. You don't need `BORecommender` as an ABC; `Myrecommender` should be called `BORecommender` instead. You can also now rename L17 to `_recommend`.

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/random.py
> +    __name__ = 'random'
Newline

2023-03-21 17:24 UTC, yrahul3910 commented on src/recommenders/random.py
> +    def __recommend(self):
`_recommend`

2023-03-24 02:53 UTC, yrahul3910 requested changes

2023-03-24 02:53 UTC, yrahul3910 commented on src/recommenders/base.py
> +    def __init__(self, stats_df: pd.DataFrame, player_name):
@korchiev Add a type hint please.

2023-03-24 02:53 UTC, yrahul3910 commented on src/recommenders/base.py
> +    def dump_to(self, filename, var_names):
@korchiev Please rename.

2023-03-24 02:53 UTC, yrahul3910 commented on src/recommenders/bi.py
> +    __name__ = 'bayesian inference'
@korchiev

2023-03-24 02:53 UTC, yrahul3910 commented on src/recommenders/random.py
> +    __name__ = 'random'
@korchiev

2023-03-24 02:53 UTC, yrahul3910 commented on src/recommenders/random.py
> +    def __recommend(self):
@korchiev Is this changed?

2023-03-24 03:21 UTC, yrahul3910 commented
lgtm

2023-03-24 03:21 UTC, yrahul3910 approved these changes

2023-03-24 03:22 UTC, vodelya approved these changes
approved

2023-03-24 03:22 UTC, merged